/* Generated by Yosys 0.69 (git sha1 9f75ca1f9, Release, GNU /usr/bin/c++ 13.3.0) */

module mult_array(clk, rst_n, a, b, p);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output [7:0] p;
  wire [7:0] p;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire [4:0] c3;
  wire \fa_row1_0.sum ;
  wire \fa_row2_0.sum ;
  wire \fa_row3_0.sum ;
  wire \fa_row3_1.sum ;
  wire \fa_row3_2.sum ;
  wire \fa_row3_3.sum ;
  wire [7:0] p_comb;
  sky130_fd_sc_hd__clkinv_1 _039_ (
    .A(a_reg[1]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _040_ (
    .A(b_reg[1]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and2_0 _041_ (
    .A(a_reg[0]),
    .B(b_reg[0]),
    .X(p_comb[0])
  );
  sky130_fd_sc_hd__and2_0 _042_ (
    .A(a_reg[1]),
    .B(b_reg[2]),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _043_ (
    .A(b_reg[2]),
    .B(a_reg[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand4_1 _044_ (
    .A(a_reg[1]),
    .B(a_reg[0]),
    .C(b_reg[0]),
    .D(b_reg[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _045_ (
    .A(b_reg[1]),
    .B(a_reg[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and4_1 _046_ (
    .A(a_reg[1]),
    .B(b_reg[0]),
    .C(b_reg[1]),
    .D(a_reg[2]),
    .X(_006_)
  );
  sky130_fd_sc_hd__o311ai_0 _047_ (
    .A1(_000_),
    .A2(a_reg[0]),
    .A3(_001_),
    .B1(a_reg[2]),
    .C1(b_reg[0]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o2111ai_1 _048_ (
    .A1(a_reg[0]),
    .A2(a_reg[2]),
    .B1(b_reg[0]),
    .C1(a_reg[1]),
    .D1(b_reg[1]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3_1 _049_ (
    .A(a_reg[1]),
    .B(b_reg[1]),
    .C(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _050_ (
    .A1(_007_),
    .A2(_009_),
    .B1(_003_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _051_ (
    .A(b_reg[0]),
    .B(a_reg[3]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _052_ (
    .A(_005_),
    .B(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _053_ (
    .A(_008_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xor3_1 _054_ (
    .A(_002_),
    .B(_010_),
    .C(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand3_1 _055_ (
    .A(a_reg[0]),
    .B(b_reg[3]),
    .C(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _056_ (
    .A(a_reg[1]),
    .B(b_reg[3]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _057_ (
    .A(b_reg[2]),
    .B(a_reg[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _058_ (
    .A1(_004_),
    .A2(_005_),
    .B1(_011_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _059_ (
    .A1(b_reg[1]),
    .A2(a_reg[3]),
    .B1(_006_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor3_1 _060_ (
    .A(_017_),
    .B(_018_),
    .C(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21ai_0 _061_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_017_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2b_1 _062_ (
    .A(_020_),
    .B_N(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__maj3_1 _063_ (
    .A(_002_),
    .B(_010_),
    .C(_013_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _064_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _065_ (
    .A(_016_),
    .B(_024_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _066_ (
    .A(_015_),
    .B(_025_),
    .Y(\fa_row3_1.sum )
  );
  sky130_fd_sc_hd__nand2_1 _067_ (
    .A(a_reg[3]),
    .B(b_reg[3]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _068_ (
    .A(b_reg[2]),
    .B(a_reg[3]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _069_ (
    .A1(_021_),
    .A2(_023_),
    .B1(_020_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _070_ (
    .A_N(_018_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _071_ (
    .A(b_reg[2]),
    .B(a_reg[3]),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor3_1 _072_ (
    .A(_018_),
    .B(_027_),
    .C(_028_),
    .X(_031_)
  );
  sky130_fd_sc_hd__maj3_1 _073_ (
    .A(_015_),
    .B(_016_),
    .C(_024_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _074_ (
    .A(a_reg[2]),
    .B(b_reg[3]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__maj3_1 _075_ (
    .A(_031_),
    .B(_032_),
    .C(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__a21oi_1 _076_ (
    .A1(_030_),
    .A2(_034_),
    .B1(_026_),
    .Y(c3[4])
  );
  sky130_fd_sc_hd__xor2_1 _077_ (
    .A(_031_),
    .B(_032_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _078_ (
    .A(_033_),
    .B(_035_),
    .Y(\fa_row3_2.sum )
  );
  sky130_fd_sc_hd__xnor3_1 _079_ (
    .A(_026_),
    .B(_030_),
    .C(_034_),
    .X(\fa_row3_3.sum )
  );
  sky130_fd_sc_hd__a21oi_1 _080_ (
    .A1(a_reg[0]),
    .A2(b_reg[3]),
    .B1(_014_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _081_ (
    .A(_015_),
    .SLEEP(_036_),
    .X(\fa_row3_0.sum )
  );
  sky130_fd_sc_hd__and3_1 _082_ (
    .A(_003_),
    .B(_007_),
    .C(_009_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _083_ (
    .A(_010_),
    .B(_037_),
    .Y(\fa_row2_0.sum )
  );
  sky130_fd_sc_hd__a22oi_1 _084_ (
    .A1(a_reg[1]),
    .A2(b_reg[0]),
    .B1(b_reg[1]),
    .B2(a_reg[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _085_ (
    .A(_004_),
    .SLEEP(_038_),
    .X(\fa_row1_0.sum )
  );
  sky130_fd_sc_hd__dfrtp_1 _086_ (
    .CLK(clk),
    .D(a[0]),
    .Q(a_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _087_ (
    .CLK(clk),
    .D(a[1]),
    .Q(a_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _088_ (
    .CLK(clk),
    .D(a[2]),
    .Q(a_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _089_ (
    .CLK(clk),
    .D(a[3]),
    .Q(a_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _090_ (
    .CLK(clk),
    .D(b[0]),
    .Q(b_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _091_ (
    .CLK(clk),
    .D(b[1]),
    .Q(b_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _092_ (
    .CLK(clk),
    .D(b[2]),
    .Q(b_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _093_ (
    .CLK(clk),
    .D(b[3]),
    .Q(b_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk),
    .D(p_comb[0]),
    .Q(p[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk),
    .D(\fa_row1_0.sum ),
    .Q(p[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk),
    .D(\fa_row2_0.sum ),
    .Q(p[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk),
    .D(\fa_row3_0.sum ),
    .Q(p[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(\fa_row3_1.sum ),
    .Q(p[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(\fa_row3_2.sum ),
    .Q(p[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(\fa_row3_3.sum ),
    .Q(p[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(c3[4]),
    .Q(p[7]),
    .RESET_B(rst_n)
  );
  assign p_comb[7:1] = { c3[4], \fa_row3_3.sum , \fa_row3_2.sum , \fa_row3_1.sum , \fa_row3_0.sum , \fa_row2_0.sum , \fa_row1_0.sum  };
  assign c3[0] = 1'h0;
endmodule
